In [9]:
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
ds_raca = pd.read_csv('Raca_Casos_2020.csv',  sep=';')
ds_raca

,Reg.Metropolit/RIDE de notific,Ign/Branco,Branca,Preta,Amarela,Parda,Indigena,Total
0,35010 Sao Paulo - SP,974,1961,215,49,1068,10,4277
1,35020 Baixada Santista - SP,761,1217,120,11,935,9,3053
2,35030 Campinas - SP,4153,3931,333,47,1634,3,10101
3,35041 V.Paraiba/Lit Nort 1 -SP,130,825,44,7,185,4,1195
4,35042 V.Paraiba/Lit Nort 2 -SP,285,3187,165,28,899,2,4566
5,35043 V.Paraiba/Lit Nort 3 -SP,3822,6501,441,49,1432,43,12288
6,35044 V.Paraiba/Lit Nort 4 -SP,1438,2754,180,23,492,13,4900
7,35045 V.Paraiba/Lit Nort 5 -SP,545,642,57,10,528,2,1784
8,35050 Jundiai - SP,257,64,3,-,36,-,360
9,35060 Piracicaba - SP,2647,5776,422,53,1099,10,10007
10,35070 Sorocaba - SP,488,3101,227,14,588,2,4420
11,35900 Fora de Reg.Metrop. - SP,17020,103073,5314,999,27752,100,154258
12,Total,32520,133032,7521,1290,36648,198,211209

In [7]:
ds_escolaridade = pd.read_csv('Escolaridade_Casos_2020.csv',  sep=';')
ds_escolaridade

,Reg.Metropolit/RIDE de notific,Ign/Branco,Analfabeto,1 a 4 serie incompleta do EF,4 serie completa do EF,5 a 8 serie incompleta do EF,Ensino fundamental completo,Ensino medio incompleto,Ensino medio completo,Educacao superior incompleta,Educacao superior completa,Nao se aplica,Total
0,35010 Sao Paulo - SP,1895,12,145,76,216,150,233,811,122,318,299,4277
1,35020 Baixada Santista - SP,1499,6,93,51,196,76,143,426,56,132,375,3053
2,35030 Campinas - SP,6553,19,214,119,334,242,314,1342,164,331,469,10101
3,35041 V.Paraiba/Lit Nort 1 -SP,536,1,26,16,41,26,61,279,18,60,131,1195
4,35042 V.Paraiba/Lit Nort 2 -SP,1092,14,167,133,321,273,371,1432,149,377,237,4566
5,35043 V.Paraiba/Lit Nort 3 -SP,8247,10,169,127,376,225,394,1681,133,396,530,12288
6,35044 V.Paraiba/Lit Nort 4 -SP,3555,4,62,58,94,55,115,554,55,148,200,4900
7,35045 V.Paraiba/Lit Nort 5 -SP,988,5,41,25,56,58,95,254,41,88,133,1784
8,35050 Jundiai - SP,255,-,7,1,4,5,11,34,4,15,24,360
9,35060 Piracicaba - SP,5402,38,313,276,462,355,405,1514,171,601,470,10007
10,35070 Sorocaba - SP,1840,20,134,100,364,162,311,918,69,165,337,4420
11,35900 Fora de Reg.Metrop. - SP,46336,938,7710,5253,11992,8045,11556,38824,3931,12049,7624,154258
12,Total,78198,1067,9081,6235,14456,9672,14009,48069,4913,14680,10829,211209

In [8]:
ds_dengue = ds_escolaridade.merge(ds_raca, on='Reg.Metropolit/RIDE de notific')

ds_dengue

,Reg.Metropolit/RIDE de notific,Ign/Branco_x,Analfabeto,1 a 4 serie incompleta do EF,4 serie completa do EF,5 a 8 serie incompleta do EF,Ensino fundamental completo,Ensino medio incompleto,Ensino medio completo,Educacao superior incompleta,Educacao superior completa,Nao se aplica,Total_x,Ign/Branco_y,Branca,Preta,Amarela,Parda,Indigena,Total_y
0,35010 Sao Paulo - SP,1895,12,145,76,216,150,233,811,122,318,299,4277,974,1961,215,49,1068,10,4277
1,35020 Baixada Santista - SP,1499,6,93,51,196,76,143,426,56,132,375,3053,761,1217,120,11,935,9,3053
2,35030 Campinas - SP,6553,19,214,119,334,242,314,1342,164,331,469,10101,4153,3931,333,47,1634,3,10101
3,35041 V.Paraiba/Lit Nort 1 -SP,536,1,26,16,41,26,61,279,18,60,131,1195,130,825,44,7,185,4,1195
4,35042 V.Paraiba/Lit Nort 2 -SP,1092,14,167,133,321,273,371,1432,149,377,237,4566,285,3187,165,28,899,2,4566
5,35043 V.Paraiba/Lit Nort 3 -SP,8247,10,169,127,376,225,394,1681,133,396,530,12288,3822,6501,441,49,1432,43,12288
6,35044 V.Paraiba/Lit Nort 4 -SP,3555,4,62,58,94,55,115,554,55,148,200,4900,1438,2754,180,23,492,13,4900
7,35045 V.Paraiba/Lit Nort 5 -SP,988,5,41,25,56,58,95,254,41,88,133,1784,545,642,57,10,528,2,1784
8,35050 Jundiai - SP,255,-,7,1,4,5,11,34,4,15,24,360,257,64,3,-,36,-,360
9,35060 Piracicaba - SP,5402,38,313,276,462,355,405,1514,171,601,470,10007,2647,5776,422,53,1099,10,10007
10,35070 Sorocaba - SP,1840,20,134,100,364,162,311,918,69,165,337,4420,488,3101,227,14,588,2,4420
11,35900 Fora de Reg.Metrop. - SP,46336,938,7710,5253,11992,8045,11556,38824,3931,12049,7624,154258,17020,103073,5314,999,27752,100,154258
12,Total,78198,1067,9081,6235,14456,9672,14009,48069,4913,14680,10829,211209,32520,133032,7521,1290,36648,198,211209

## Análise Exploratória